/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 bitcoin.gltf --transform
Author: Raakesh.Madan (https://sketchfab.com/Raakesh.Madan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bitcoin-btc-gold-lowpoly-d544ea193d2a46899c78ea63031f203b
Title: Bitcoin BTC Gold Lowpoly
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bitcoin-transformed.glb', 'aggressive')
  return (
    <group {...props} dispose={null}>
      <group scale={0.02}>
        <group position={[-122.32, -120, -77.56]} scale={100}>
          <group position={[0.45, 0, 1]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
            <mesh geometry={nodes.C______rculo_B______zier_001_0_1.geometry} material={materials.Material_BTC} position={[1.22, -0.78, 1.02]}  rotation={[0, Math.PI / 2, 0]} />
          </group>
        </group>
      </group>
    </group>
  )
}

export default Model

useGLTF.preload('/bitcoin-transformed.glb')
