/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 cube.gltf --transform
Author: lildrstrange11 (https://sketchfab.com/lildrstrange11)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kevin-the-cube-9786cbc1a5dc4a8ba5361813c1283bb3
Title: Kevin The Cube
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cube-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Material} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

export default Model

useGLTF.preload('/cube-transformed.glb')
