/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 train.gltf --transform
Author: andysedano (https://sketchfab.com/andysedano)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/train-f5fa509073504c43b139e80ab62b6d11
Title: Train
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/train-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={3}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.lambert8SG} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.lambert6SG} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.lambert7SG} />
        </group>
      </group>
    </group>
  )
}

export default Model
useGLTF.preload('/train-transformed.glb')
